---
port: 4000
host: 0.0.0.0

title: My Cuddle Club
header-img: img/home-bg.jpg
email:
description: "All your baby needs delivered to your doorstep"
baseurl: ""
url: "http://mycuddleclub.github.io/cuddleclub-site/"
twitter_username:
github_username:
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
