---
port: 4000
host: 0.0.0.0

title: Clean Blog
header-img: img/home-bg.jpg
email: 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: /
url: "http://mycuddleclub.github.io/cuddleclub-site/"
twitter_username: 
github_username:  mycuddleclub
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
